repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/UCSolarCarTeam/Solar-Car-Pre-commit
    rev: v1.1.0
    hooks:
    -   id: solar-car-commit-msg
        stages: [commit-msg]
