apiVersion: 1

datasources:
  # configruation setup viewable here: https://github.com/grafana/mqtt-datasource/blob/main/src/ConfigEditor.tsx
  - name: MQTT
    uid: grafana-mqtt-datasource
    type: grafana-mqtt-datasource
    editable: true
    isDefault: true
    secureJsonData:
      password: ${MQTT_PASSWORD}
    jsonData:
      username: ${MQTT_USERNAME}
      uri: host.docker.internal:1883

  - name: grafana-postgresql-datasource
    uid: grafana-postgresql-datasource
    type: postgres
    url: ${POSTGRES_HOST}
    database: postgres
    user: ${POSTGRES_USERNAME}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
      minInterval: 1m
      maxOpenConns: 10
      maxIdleConns: 10
      maxLifetime: 14400
    editable: true
  # - name: Postgres
  #   type: postgres
  #   url: postgres:5432
  #   user: yourusername
  #   secureJsonData:
  #     password: "yourpassword"
  #   jsonData:
  #     database: mqtt
  #     sslmode: "disable" # disable/require/verify-ca/verify-full
