apiVersion: 1

datasources:
  # configruation setup viewable here: https://github.com/grafana/mqtt-datasource/blob/main/src/ConfigEditor.tsx
  - name: MQTT
    type: grafana-mqtt-datasource
    editable: true
    isDefault: true
    secureJsonData:
      password: ${MQTT_PASSWORD}
    jsonData:
      username: ${MQTT_USERNAME}
      uri: host.docker.internal:1883

  - name: grafana-postgresql-datasource
    type: postgres
    url: l6yyro58r7.wy9edrssy5.tsdb.cloud.timescale.com:38572
    database: tsdb
    user: ${POSTGRES_USERNAME}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "require"
      postgresVersion: 9.3
      timescaledb: true
      minInterval: 1m
      maxOpenConns: 100
      maxIdleConns: 100
      maxLifetime: 14400
    editable: true
  # - name: Postgres
  #   type: postgres
  #   url: postgres:5432
  #   user: yourusername
  #   secureJsonData:
  #     password: "yourpassword"
  #   jsonData:
  #     database: mqtt
  #     sslmode: "disable" # disable/require/verify-ca/verify-full
