{
 "title": "Das Telemetry Base Dashboard (History)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Range and Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pack State Of Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"PackStateOfCharge\"\nFROM telemetry_packet\nWHERE $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Packet (History)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"PackCurrent\", \"PackVoltage\", \"PackStateOfCharge\", \"PackAmphours\", \"RegenBraking\" \nFROM telemetry_packet\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"EnergyConsumed\" \nFROM lap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Total Power In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT\n  \"timestamp\" AS time,\n  \"TotalPowerIn\"\nFROM lap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Average Pack Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"AveragePackCurrent\"\nFROM lap \nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"TotalPowerOut\" \nFROM lap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Battery Seconds Remaining",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"BatterySecondsRemaining\" \nFROM lap \nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  { "title": "Speed & Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average Speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"AverageSpeed\" \nFROM lap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Lap Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"LapTime\" \nFROM lap \nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  { "title": "Driving Behavior and Safety", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Driving Behavior",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"Acceleration\", \"BrakeSwitchDigital\", \"LeftSignalStatus\", \"RightSignalStatus\" \nFROM telemetry_packet \nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Safety",
   "type": "timeseries",
   "description": "Critical system errors or safety trips within the battery management system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"ProximitySensor1\", \"timestamp\", \"ProtectionTrip\", \"MalfunctionIndicatorActive\", \"ArrayContactorError\"\nFROM telemetry_packet \nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Total Distance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tsdb",
     "rawSql": "SELECT \"timestamp\", \"Distance\" \nFROM lap \nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY \"timestamp\" ASC"
    }
   ]
  }
 ]
}